# Use Nginx base image
FROM nginx:latest

# Copy configuration files
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80
